In [1]:
%pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [14]:
abnb = pd.read_csv("data/ABNB.csv")
tsa = pd.read_csv("data/tsa_2025.csv")
cpi = pd.read_csv("data/fred_cpi_lodging_away_from_home.csv")

In [11]:
abnb.head()

,date,ticker,volume,open,close,high,low,window_start,transactions
0,2025-01-02,ABNB,2606269,131.87,131.48,134.230,130.4100,1735794000000000000,51821
1,2025-01-03,ABNB,3607355,131.98,135.71,136.360,131.9400,1735880400000000000,62530
2,2025-01-06,ABNB,4174471,137.00,135.20,138.100,134.5800,1736139600000000000,69444
3,2025-01-07,ABNB,4290458,135.35,131.29,136.765,130.8096,1736226000000000000,64384
4,2025-01-08,ABNB,3204678,131.20,130.80,131.630,130.1000,1736312400000000000,51095

In [15]:
tsa.head()

     Date    Numbers
0  1/1/25  2,317,817
1  1/2/25  2,612,162
2  1/3/25  2,563,751
3  1/4/25  2,543,303
4  1/5/25  2,579,257

In [13]:
cpi.head()

  observation_date  CUSR0000SEHB
0       2025-06-01       182.607
1       2025-07-01       180.824
2       2025-08-01       184.457

In [16]:
# convert Date column to datetime
tsa['Date'] = pd.to_datetime(tsa['Date'])

# filter for summer period
tsa_summer = tsa[
    (tsa['Date'] >= '2025-06-01') &
    (tsa['Date'] <= '2025-08-15')
]

tsa_summer.head()

/var/folders/4k/02060mxx2w7f0qm05q4snwx80000gn/T/ipykernel_98157/2356625188.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  tsa['Date'] = pd.to_datetime(tsa['Date'])

          Date    Numbers
151 2025-06-01  2,825,055
152 2025-06-02  2,642,700
153 2025-06-03  2,213,336
154 2025-06-04  2,364,375
155 2025-06-05  2,798,927

In [17]:
# convert date
abnb['date'] = pd.to_datetime(abnb['date'])

# filter summer
abnb_summer = abnb[
    (abnb['date'] >= '2025-06-01') &
    (abnb['date'] <= '2025-08-15')
]

abnb_summer.head()

,date,ticker,volume,open,close,high,low,window_start,transactions
102,2025-06-02,ABNB,5223064,128.85,129.62,129.7700,127.985,1748836800000000000,77434
103,2025-06-03,ABNB,5809271,129.50,132.90,133.4900,128.950,1748923200000000000,76850
104,2025-06-04,ABNB,4501382,132.28,133.51,134.8550,131.640,1749009600000000000,74673
105,2025-06-05,ABNB,5859127,133.50,137.29,137.8025,133.500,1749096000000000000,87427
106,2025-06-06,ABNB,9053459,139.18,140.64,143.8799,138.950,1749182400000000000,128282

In [18]:
# convert date
cpi['observation_date'] = pd.to_datetime(cpi['observation_date'])

# filter summer
cpi_summer = cpi[
    (cpi['observation_date'] >= '2025-06-01') &
    (cpi['observation_date'] <= '2025-08-15')
]

cpi_summer.head()

  observation_date  CUSR0000SEHB
0       2025-06-01       182.607
1       2025-07-01       180.824
2       2025-08-01       184.457