In [1]:
%pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [7]:
abnb = pd.read_csv("data/ABNB.csv")
tsa = pd.read_csv("data/tsa_passenger_volumes.csv")
cpi = pd.read_csv("data/fred_cpi_lodging_away_from_home.csv")

In [11]:
abnb.head()

,date,ticker,volume,open,close,high,low,window_start,transactions
0,2025-01-02,ABNB,2606269,131.87,131.48,134.230,130.4100,1735794000000000000,51821
1,2025-01-03,ABNB,3607355,131.98,135.71,136.360,131.9400,1735880400000000000,62530
2,2025-01-06,ABNB,4174471,137.00,135.20,138.100,134.5800,1736139600000000000,69444
3,2025-01-07,ABNB,4290458,135.35,131.29,136.765,130.8096,1736226000000000000,64384
4,2025-01-08,ABNB,3204678,131.20,130.80,131.630,130.1000,1736312400000000000,51095

In [12]:
tsa.head()

       Date  Numbers
0  4/9/2026  2691308
1  4/8/2026  2278770
2  4/7/2026  2207180
3  4/6/2026  2705640
4  4/5/2026  2561932

In [13]:
cpi.head()

  observation_date  CUSR0000SEHB
0       2025-06-01       182.607
1       2025-07-01       180.824
2       2025-08-01       184.457